### PR TITLE
Post menu item/edit 1

### PR DESCRIPTION
**Pull request by koray-eren**

### CODE REVIEW

**Comment by koray-eren** [comment]
the test CI failing - is that because we need to set the DB to reset before each run (and/or the alternative way discussed today with the gems)?

**Comment by leighpoulier** [comment]
> the test CI failing - is that because we need to set the DB to reset before each run (and/or the alternative way discussed today with the gems)?

Yeah i think so - the test database is empty.  I think we have to assume that it will always be empty at the start of testing

**Comment by leighpoulier** [comment]
> > the test CI failing - is that because we need to set the DB to reset before each run (and/or the alternative way discussed today with the gems)?
> 
> Yeah i think so - the test database is empty. I think we have to assume that it will always be empty at the start of testing

From the test log, it creates the database, then runs `bundle exec rails db:create db:schema:load`
So i think we should do that locally to reset our database (which we seeded the other day) to be completely bare with only the tables setup.

**Comment by leighpoulier** [comment]
> > > the test CI failing - is that because we need to set the DB to reset before each run (and/or the alternative way discussed today with the gems)?
> > 
> > 
> > Yeah i think so - the test database is empty. I think we have to assume that it will always be empty at the start of testing
> 
> From the test log, it creates the database, then runs `bundle exec rails db:create db:schema:load` So i think we should do that locally to reset our database (which we seeded the other day) to be completely bare with only the tables setup.

This is what i used:
`bundle exec rails db:drop db:create db:schema:load RAILS_ENV=test`

**Comment by koray-eren** [comment]
> > > > the test CI failing - is that because we need to set the DB to reset before each run (and/or the alternative way discussed today with the gems)?
> > > 
> > > 
> > > Yeah i think so - the test database is empty. I think we have to assume that it will always be empty at the start of testing
> > 
> > 
> > From the test log, it creates the database, then runs `bundle exec rails db:create db:schema:load` So i think we should do that locally to reset our database (which we seeded the other day) to be completely bare with only the tables setup.
> 
> This is what i used: `bundle exec rails db:drop db:create db:schema:load RAILS_ENV=test`

ahh yep makes sense - so that local test env == server test env

**Review by leighpoulier — APPROVED** [review]

**Pull request merged**
